plugins {
    id 'application'
}

group = 'com.wharvex.budget'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'info.picocli:picocli:4.7.7'
    runtimeOnly 'org.postgresql:postgresql:42.7.8'

    testImplementation platform('org.junit:junit-bom:5.12.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.wharvex.budget.BudgetForecastCli'
}

tasks.named('test') {
    useJUnitPlatform()
}
