-- budget-03-ddl-create-account-table.sql
CREATE TABLE account (
    account_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR(255) NOT NULL,
    balance DECIMAL(19,2)
);
